CREATE TABLE VALIDATOR(
VALIDATOR_ID INT IDENTITY(1,1) PRIMARY KEY, -- UNIQUE OLMALI
VALIDATOR_NO INT NOT NULL UNIQUE,
SERIAL_NO VARCHAR(10) NOT NULL UNIQUE,
GSM_NO VARCHAR(15) NOT NULL,
CREATED_DATE DATETIME DEFAULT GETDATE(),
ISACTIVE BIT DEFAULT 1 -- AKTÝF DURUM
)


-- LINES TABLOSU
CREATE TABLE LINES (
LINE_ID INT IDENTITY(1,1) PRIMARY KEY,
LINE_CODE VARCHAR(20) NOT NULL UNIQUE,
LINE_NAME VARCHAR(100) NOT NULL,
ROUTE_INFO VARCHAR(100), 
ISACTIVE BIT DEFAULT 1,
CREATED_DATE DATETIME DEFAULT GETDATE()
)


CREATE TABLE VEHICLE(
VEHICLE_ID INT IDENTITY(1,1) PRIMARY KEY,
PLATE VARCHAR(15) NOT NULL UNIQUE,
VALIDATOR_NO INT NOT NULL UNIQUE, -- UNIQUE OLMALI, FOREIGN KEY
VEHICLE_BRAND VARCHAR(50) NOT NULL,
VEHICLE_MODEL VARCHAR(50) NOT NULL,
LINE_ID INT,
CREATED_DATE DATETIME DEFAULT GETDATE(),
ISACTIVE BIT DEFAULT 1,

FOREIGN KEY (VALIDATOR_NO) REFERENCES VALIDATOR(VALIDATOR_NO),
FOREIGN KEY (LINE_ID) REFERENCES LINES(LINE_ID)
)


CREATE TABLE CARDTYPES(
CARD_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY,
CARD_TYPE VARCHAR(50) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE >= 0 ), -- ÜCRET 0IN ALTI OLAMAZ
ISACTIVE BIT DEFAULT 1
)


CREATE TABLE CARDS(
CARD_ID INT IDENTITY(1,1) PRIMARY KEY, -- UNIQUE OLMALI
CARD_NO INT NOT NULL UNIQUE CHECK (CARD_NO BETWEEN 10000 AND 99999), -- 5 DIGIT NUMERIC OLACAK,UNIQUE, NOT DUPLICATE 
CARD_TYPE_ID INT NOT NULL,
BALANCE DECIMAL(10,2) NOT NULL CHECK (BALANCE > 0), -- BAKÝYE 0'DAN FAZLA OLMALI
EXPIRATION_DATE DATETIME NOT NULL,
ISACTIVE BIT DEFAULT 1,
MODIFIED_DATE DATETIME NOT NULL

FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARDTYPES(CARD_TYPE_ID)
)


-- KURUM TABLOSU
CREATE TABLE INSTITUTION (
INSTITUTION_ID INT IDENTITY(1,1) PRIMARY KEY,
INSTITUTION_NAME VARCHAR(50) NOT NULL, 
INSTITUTION_ADDRESS VARCHAR(100) NOT NULL,
INSTITUTION_GSM_NO VARCHAR(15) NOT NULL
)


-- BAYÝ TABLOSU
CREATE TABLE DEALER(
DEALER_ID INT IDENTITY(1,1) PRIMARY KEY,
DEALER_NAME VARCHAR(50) NOT NULL,
INSTITUTION_ID INT NOT NULL UNIQUE,
DEALER_GSM_NO VARCHAR(15) NOT NULL,
DEALER_ADRESS VARCHAR(100) NOT NULL,

FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID)
)


-- POS TABLOSU
CREATE TABLE POS (
POS_ID INT IDENTITY(1,1) PRIMARY KEY,
POS_CODE VARCHAR(15) NOT NULL,
POS_LOCATION VARCHAR(50) NOT NULL,
DEALER_ID INT NOT NULL UNIQUE, 

FOREIGN KEY (DEALER_ID) REFERENCES DEALER(DEALER_ID)
)


-- CÝHAZ TÝPÝ TABLOSU
CREATE TABLE DEVICE_TYPES (
DEVICE_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY,
DEVICE_TYPE_NAME VARCHAR(50) NOT NULL,
DESCRIPTION VARCHAR(200),
ISACTIVE BIT DEFAULT 1,
CREATED_DATE DATETIME DEFAULT GETDATE()
)


-- SÝSTME KAYITLARI ÝÇÝN TABLO
CREATE TABLE SYSTEM_LOG (
LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
TRANSACTION_ID INT, -- TRANSACTIONS tablosu ile iliþki
SYSTEM_TIME DATETIME DEFAULT GETDATE(),
LOG_MESSAGE VARCHAR(500),
LOG_LEVEL VARCHAR(20), -- 'INFO', 'ERROR', 'WARNING'
CREATED_DATE DATETIME DEFAULT GETDATE()
)


-- iÞLEM TABLOSU
CREATE TABLE TRANSACTIONS(
TRANSACTION_ID INT IDENTITY(1,1) PRIMARY KEY,
VEHICLE_ID INT NOT NULL,
CARD_ID INT NOT NULL,
CARD_NO INT NOT NULL,
CARD_TYPE_ID INT NOT NULL,
DEVICE_TYPE_ID INT DEFAULT 1, --1 : VALIDATOR
TRANSACTION_DATE DATETIME NOT NULL,
SPENT_AMOUNT DECIMAL(10,2) NOT NULL,
REMAINING_BALANCE DECIMAL(10,2),
PRE_BALANCE DECIMAL(10,2) NOT NULL,
SYSTEM_TIME_ DATETIME DEFAULT GETDATE(),
LOCATION_INFO VARCHAR(100),

FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID),
FOREIGN KEY (CARD_ID) REFERENCES CARDS(CARD_ID),
FOREIGN KEY (DEVICE_TYPE_ID) REFERENCES DEVICE_TYPES(DEVICE_TYPE_ID),
FOREIGN KEY (CARD_ID) REFERENCES CARDS(CARD_ID),
)


CREATE TABLE TOPUPTRANSACTIONS(
TOP_UP_TRANSACTION_ID INT IDENTITY(1,1) PRIMARY KEY,
CARD_ID INT,
POS_ID INT,
DEALER_ID INT,
INSTITUTION_ID INT,
AMOUNT DECIMAL(10,2),
TOP_UP_CHANNEL NVARCHAR(50), -- DEALER, KIOSK, WEB, MOBILE
TOP_UP_TRANSACTION_DATE DATETIME

FOREIGN KEY (CARD_ID) REFERENCES CARDS(CARD_ID),
FOREIGN KEY (POS_ID) REFERENCES POS(POS_ID),
FOREIGN KEY (DEALER_ID) REFERENCES DEALER(DEALER_ID),
FOREIGN KEY (INSTITUTION_ID) REFERENCES INSTITUTION(INSTITUTION_ID),
)
