CREATE DATABASE DENEME2
USE DENEME2

CREATE TABLE VALIDATOR(
VALIDATOR_ID INT IDENTITY(1,1) PRIMARY KEY, -- UNIQUE OLMALI
VALIDATOR_NO INT NOT NULL UNIQUE,
SERIAL_NO VARCHAR(10) NOT NULL UNIQUE,
GSM_NO VARCHAR(15) NOT NULL,
ISACTIVE BIT DEFAULT 1 -- AKTÝF DURUM
)


CREATE TABLE VEHICLE(
VEHICLE_ID INT IDENTITY(1,1) PRIMARY KEY,
PLATE VARCHAR(15) NOT NULL UNIQUE,
VALIDATOR_NO INT NOT NULL UNIQUE, -- UNIQUE OLMALI, FOREIGN KEY
VEHICLE_BRAND VARCHAR(50) NOT NULL,
VEHICLE_MODEL VARCHAR(50) NOT NULL,
ISACTIVE BIT DEFAULT 1,

FOREIGN KEY (VALIDATOR_NO) REFERENCES VALIDATOR(VALIDATOR_NO)
)


CREATE TABLE CARDTYPES(
CARD_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY,
CARD_TYPE VARCHAR(50) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL CHECK (PRICE >= 0 ), -- ÜCRET 0IN ALTI OLAMAZ
ISACTIVE BIT DEFAULT 1
)


CREATE TABLE CARDS(
CARD_ID INT IDENTITY(1,1) PRIMARY KEY, -- UNIQUE OLMALI
CARD_NO INT NOT NULL UNIQUE, -- 5 DIGIT NUMERIC OLACAK,UNIQUE, NOT DUPLICATE 
CARD_TYPE_ID INT NOT NULL,
CARD_TYPE VARCHAR(50) NOT NULL,
BALANCE DECIMAL(10,2) NOT NULL CHECK (BALANCE > 0), -- BAKÝYE 0'DAN FAZLA OLMALI
EXPIRATION_DATE DATETIME NOT NULL,
ISACTIVE BIT DEFAULT 1,
MODIFIED_DATE DATETIME NOT NULL

FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARDTYPES(CARD_TYPE_ID),
FOREIGN KEY (CARD_TYPE) REFERENCES CARDTYPES(CARD_TYPE)
)


CREATE TABLE TRANSACTIONS(
TRANSACTION_ID INT IDENTITY(1,1) PRIMARY KEY,
VEHICLE_ID INT NOT NULL,
CARD_ID INT NOT NULL,
CARD_NO INT NOT NULL,
CARD_TYPE_ID INT NOT NULL,
TRANSACTION_DATE DATETIME NOT NULL,
SPENT_AMOUNT DECIMAL(10,2) NOT NULL,
REMAINING_BALANCE DECIMAL(10,2) NOT NULL,

FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE(VEHICLE_ID),
FOREIGN KEY (CARD_ID) REFERENCES CARDS(CARD_ID)
)