-- PERFORMANS ÝÇÝN ÝNDEXLER
CREATE INDEX IX_TRANSACTIONS_DATE ON TRANSACTIONS(TRANSACTION_DATE);

CREATE INDEX IX_TRANSACTIONS_CARD_ID ON TRANSACTIONS(CARD_ID);

CREATE INDEX IX_TRANSCATIONS_VEHICLE_ID ON TRANSACTIONS(VEHICLE_ID);

CREATE INDEX IX_TOPUP_DATE ON TOPUPTRANSACTIONS(TOP_UP_TRANSACTION_DATE);

CREATE INDEX IX_TOPUP_CARD_ID ON TOPUPTRANSACTIONS(CARD_ID);

-- TRANSACTION TABLOSU ÝÇÇÝN INDEXLER
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTIONS_DATE')
CREATE INDEX IX_TRANSACTIONS_DATE ON TRANSACTIONS(TRANSACTION_DATE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTIONS_CARD_ID')
CREATE INDEX IX_TRANSACTIONS_CARD_ID ON TRANSACTIONS(CARD_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTIONS_VEHICLE_ID')
CREATE INDEX IX_TRANSACTIONS_VEHICLE_ID ON TRANSACTIONS(VEHICLE_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRANSACTIONS_CARD_TYPE_ID')
CREATE INDEX IX_TRANSACTIONS_CARD_TYPE_ID ON TRANSACTIONS(CARD_TYPE_ID);

-- TOPUPTRANSACTIONS TABLOSU ÝÇÝN INDEXLER
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TOPUP_DATE')
CREATE INDEX IX_TOPUP_DATE ON TOPUPTRANSACTIONS(TOP_UP_TRANSACTION_DATE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TOPUP_CARD_ID')
CREATE INDEX IX_TOPUP_CARD_ID ON TOPUPTRANSACTIONS(CARD_ID);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TOPUP_INSTITUTION')
CREATE INDEX IX_TOPUP_INSTITUTION ON TOPUPTRANSACTIONS(INSTITUTION_ID);

-- CARDS TABLOSU ÝÇÝN INDEXLER
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_CARDS_CARD_NO')
CREATE INDEX IX_CARDS_CARD_NO ON CARDS(CARD_NO);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_CARDS_ACTIVE')
CREATE INDEX IX_CARDS_ACTIVE ON CARDS(ISACTIVE) WHERE ISACTIVE = 1;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_CARDS_BALANCE')
CREATE INDEX IX_CARDS_BALANCE ON CARDS(BALANCE);

-- VEHICLE TABLOSU ÝÇÝN INDEXLER
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_VEHICLE_PLATE')
CREATE INDEX IX_VEHICLE_PLATE ON VEHICLE(PLATE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_VEHICLE_ACTIVE')
CREATE INDEX IX_VEHICLE_ACTIVE ON VEHICLE(ISACTIVE) WHERE ISACTIVE = 1;