-- ===============================================
-- KULLANIM ÖRNEKLERÝ
-- ===============================================
PRINT 'STORED PROCEDURE KULLANIM ÖRNEKLERÝ'

PRINT 'TOP-UP RAPORU'
PRINT '
EXEC SP_TOPUP_REPORT 
    @START_DATE = ''2024-01-01'', 
    @END_DATE = ''2025-12-31'', 
    @INSTITUTION_ID = 2;
'

PRINT 'KART KULLANIM RAPORU'
PRINT '
EXEC SP_CARD_USAGE_REPORT 
    @START_DATE = ''2025-01-01'', 
    @END_DATE = ''2025-12-31'',
    @CARD_TYPE_ID = 2;
'

PRINT 'KAPSAMLI RAPOR (BÝREYSEL KART ID ÝLE)'
PRINT '
EXEC SP_FINAL_REPORT
    @START_DATE = ''2025-01-01'', 
    @END_DATE = ''2025-12-31'',
    @REPORT_TYPE = ''ALL'',
    @CARD_ID = 1;
'

PRINT 'KAPSAMLI RAPOR (CARD TYPE ID ÝLE)'
PRINT '
EXEC SP_FINAL_REPORT
    @START_DATE = ''2025-01-01'',
    @END_DATE = ''2025-12-31'',
    @REPORT_TYPE = ''ALL'',
    @CARD_TYPE_ID = 1;
'

PRINT 'KAPSAMLI RAPOR DENEME SP'
PRINT '
EXEC SP_FINAL_REPORT_DENEME
    @START_DATE = ''2025-01-01'',
    @END_DATE = ''2025-12-31'',
    @REPORT_TYPE = ''ALL'',
    @CARD_TYPE_ID = 1;
'

PRINT 'PERIOD DASHBOARD'
PRINT '
EXEC SP_DASHBOARD_REPORT;
'

PRINT 'GELÝÞTÝRÝLMÝÞ SÝMÜLASYON'
PRINT '
EXEC SP_SIMULATEBOARDINGS 
    @START_DATE = ''2025-01-01'',
    @END_DATE = ''2025-01-31'', 
    @VEHICLE_ID = NULL,  
    @RECORD_COUNT = 10;
'

PRINT 'KART TÜRÜ EKLEME'
PRINT '
EXEC SP_ADD_CARD_TYPE
    @CARD_TYPE = ''MOTHER'',
    @PRICE = 20;
'

PRINT 'GENEL RAPOR ÜRETME'
PRINT '
EXEC SP_GENERATEREPORT
    @START_DATE = ''2025-01-01'',
    @END_DATE = ''2025-01-31'';
'

PRINT 'KART OLUÞTURMA'
PRINT '
EXEC SP_CREATECARD '



-- ===============================================
-- STORED PROCEDURE KULLANIM ÖRNEKLERÝ
-- ===============================================

-- TOP-UP RAPORU
EXEC SP_TOPUP_REPORT 
    @START_DATE = '2024-01-01', 
    @END_DATE = '2025-12-31', 
    @INSTITUTION_ID = 1;

-- KART KULLANIM RAPORU
EXEC SP_CARD_USAGE_REPORT 
    @START_DATE = '2025-01-01', 
    @END_DATE = '2025-12-31',
    @CARD_TYPE_ID = 2;

-- KAPSAMLI RAPOR (BÝREYSEL KART ID ÝLE)
EXEC SP_FINAL_REPORT
    @START_DATE = '2025-01-01', 
    @END_DATE = '2025-12-31',
    @REPORT_TYPE = 'ALL',
    @CARD_ID = 1;

-- KAPSAMLI RAPOR (CARD TYPE ID ÝLE)
EXEC SP_FINAL_REPORT
    @START_DATE = '2025-01-01',
    @END_DATE = '2025-12-31',
    @REPORT_TYPE = 'ALL',
    @CARD_TYPE_ID = 1;

-- KAPSAMLI RAPOR DENEME SP
EXEC SP_FINAL_REPORT_DENEME
    @START_DATE = '2025-01-01',
    @END_DATE = '2025-12-31',
    @REPORT_TYPE = 'ALL',
    @CARD_TYPE_ID = 1;

-- PERIOD DASHBOARD
EXEC SP_DASHBOARD_REPORT;

-- GELÝÞTÝRÝLMÝÞ SÝMÜLASYON
EXEC SP_SIMULATEBOARDINGS 
    @START_DATE = '2025-01-01',
    @END_DATE = '2025-01-31', 
    @VEHICLE_ID = NULL,  
    @RECORD_COUNT = 10;

-- KART TÜRÜ EKLEME
EXEC SP_ADD_CARD_TYPE
    @CARD_TYPE = 'MOTHER',
    @PRICE = 20;

-- GENEL RAPOR ÜRETME
EXEC SP_GENERATEREPORT
    @START_DATE = '2025-01-01',
    @END_DATE = '2025-01-31';

-- KART OLUÞTURMA
EXEC SP_CREATECARD;
