CREATE PROCEDURE SP_ADD_CARD_TYPE
    @CARD_TYPE NVARCHAR(100),
    @PRICE DECIMAL(18,2)
AS
BEGIN
    INSERT INTO CARDTYPES (CARD_TYPE, PRICE, ISACTIVE)
    VALUES (@CARD_TYPE, @PRICE, 1);
END


EXEC SP_ADD_CARD_TYPE
	@CARD_TYPE = 'MOTHER',
	@PRICE = 20;


