CREATE PROCEDURE SP_CREATECARD
@CARD_COUNT INT = 2 --  2 KART EKLENSÝN
AS
BEGIN --MAIN

	SET NOCOUNT ON

	-- DEÐÝÞKENLER
	DECLARE @COUNTER INT = 0 -- SAYAÇ
	DECLARE @RANDOM_CARD_NO INT -- RANDOM KAR NUMARASI
	DECLARE @RANDOM_BALANCE DECIMAL(10,2) -- RANDOM BAKÝYE
	DECLARE @RANDOM_CARD_TYPE_ID INT -- RANDOM KART TÝPÝ ID
	DECLARE @CARD_TYPE VARCHAR(50) -- KART TÝPÝ
	DECLARE @RANDOM_EXPIRATION_DATE DATETIME -- RANDOM BÝTÝÞ TARÝHÝ
	DECLARE @EXISTING_CARD INT -- KART EXISTS 
	DECLARE @RETRY_COUNT INT -- DENEME 
	DECLARE @SUCCESS_COUNT INT -- BAÞARLI KAYIT SAYISI


	-- EÐER KAT AKTÝF DEÐÝLSE AKTÝF KART BULUNAMAID MESAJI GÖSTER
	IF NOT EXISTS (SELECT 1 FROM CARDTYPES WHERE ISACTIVE = 1)
	BEGIN --2
		PRINT('AKTÝF KART BULUNAMADI')
		RETURN
	END --2


	-- COUNTER, KART SAYISINDAN KÜÇÜK OLDUÐU SÜRECE ÇALIÞTIR
	WHILE @COUNTER < @CARD_COUNT
	BEGIN --3
		
		SET @RETRY_COUNT = 0
		WHILE @RETRY_COUNT < 100
		BEGIN --4
			SET @RANDOM_CARD_NO = CAST(RAND() * 90000 + 10000 AS INT)
			SELECT @EXISTING_CARD = COUNT(*) FROM CARDS WHERE CARD_NO = @RANDOM_CARD_NO
			IF @EXISTING_CARD = 0 BREAK
			SET @RETRY_COUNT = @RETRY_COUNT + 1
		END --4
		IF @RETRY_COUNT >= 100
			BEGIN --5
				PRINT('BENZERSÝZ KART OLUÞTURULMADI')
			END --5
		SELECT TOP 1 @RANDOM_CARD_TYPE_ID = CARD_TYPE_ID FROM CARDTYPES WHERE ISACTIVE = 1
		ORDER BY NEWID(); -- RASTGELE SEÇER
		SET @RANDOM_BALANCE = CAST(RAND() * 500 + 500 AS DECIMAL(10,2)) -- 500 ÝLE 1000 TL ARASI EÐER +500 KOYMAZSAK 0 ÝLE 500 ARASI OLMUÞ OLUYOR
		SET @RANDOM_EXPIRATION_DATE = DATEADD(DAY,CAST(RAND()*365 * 4 + 365 AS INT) , GETDATE()) -- 365 ile 1825, 1 VE 5 YIL ARASINDA GELEBÝLÝR EÐER +365 OLMASAYDI 0 VE 4 YIL ARASI OLMUÞ OLURDU.
		
		
		BEGIN --6
			INSERT INTO CARDS (CARD_NO, CARD_TYPE_ID, BALANCE, EXPIRATION_DATE, MODIFIED_DATE)
			VALUES (@RANDOM_CARD_NO, @RANDOM_CARD_TYPE_ID, @RANDOM_BALANCE, @RANDOM_EXPIRATION_DATE, GETDATE())
			SET @COUNTER = @COUNTER + 1

			SET @SUCCESS_COUNT = @SUCCESS_COUNT + 1

		END --6
	END --3


	IF @SUCCESS_COUNT > 0
	BEGIN --4
    SELECT TOP (@CARD_COUNT)
        C.CARD_ID,
        C.CARD_NO,
        CT.CARD_TYPE,
        C.BALANCE,
        C.EXPIRATION_DATE,
        C.ISACTIVE
    FROM CARDS C
    INNER JOIN CARDTYPES CT ON C.CARD_TYPE_ID = CT.CARD_TYPE_ID
    ORDER BY C.CARD_ID DESC;

	END --4

	SELECT * FROM CARDS

END --  MAIN






EXEC SP_CREATECARD 