CREATE PROCEDURE SP_CARD_USAGE_REPORT
@START_DATE DATETIME = NULL, 
@END_DATE DATETIME = NULL,
@CARD_ID INT = NULL,
@VEHICLE_ID INT = NULL,
@CARD_TYPE_ID INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- EÐER BAÞLANGIÇ VE BÝTÝÞ TARÝHÝ NULL SEÇÝLÝRSE SON 7 GÜN ALINACAK
	-- VARSAYILAN TARÝH ARAIÐI (SON 7 GÜN)
    IF @START_DATE IS NULL SET @START_DATE = DATEADD(DAY, -7, GETDATE())
    IF @END_DATE IS NULL SET @END_DATE = GETDATE()
    
	-- BAÞLANGIÇ VE BÝTÝÞ TARÝHÝ KONTROLÜ
    IF @START_DATE >= @END_DATE
    BEGIN
		PRINT 'BAÞLANGIÇ TARÝHÝ BÝTÝÞ TARÝHÝNDEN KÜÇÜK OLMALI'
        RETURN
    END
    
    SELECT 
        -- ÝÞLEM BÝLGÝLERÝ
        T.TRANSACTION_ID AS 'TRANSACTION ID',
		T.TRANSACTION_DATE AS 'TRANSACTION DATE',
        
        -- KART BÝLGÝLERÝ
        T.CARD_ID AS 'CARD ID',
        T.CARD_NO AS 'CARD NO',
        CT.CARD_TYPE AS 'CARD TYPE',
        
        -- CÝHAZ BÝLGÝLERÝ
        VAL.VALIDATOR_NO AS 'VALIDATOR NO',
        VAL.SERIAL_NO AS 'VALIDATOR SERIAL NO',
        
        -- KONUM BÝLGÝLERÝ
        V.PLATE AS 'PLATE',
        V.VEHICLE_BRAND + ' ' + V.VEHICLE_MODEL AS 'VEHICLE INFO',
        
        -- FÝNANSAL BÝLGÝLER
		T.PRE_BALANCE AS 'PRE BALANCE',
		T.SPENT_AMOUNT AS 'SPENT AMOUNT',
		T.REMAINING_BALANCE AS 'REMAINING BALANCE'
        
    FROM TRANSACTIONS T
    INNER JOIN CARDS C ON T.CARD_ID = C.CARD_ID
    INNER JOIN CARDTYPES CT ON C.CARD_TYPE_ID = CT.CARD_TYPE_ID
    INNER JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
    INNER JOIN VALIDATOR VAL ON V.VALIDATOR_NO = VAL.VALIDATOR_NO
    
    WHERE 
	-- TARÝH ARALIÐI FÝLTRESÝ
        CAST(T.TRANSACTION_DATE AS DATE) BETWEEN CAST(@START_DATE AS DATE) AND CAST(@END_DATE AS DATE)
        AND (@CARD_ID IS NULL OR T.CARD_ID = @CARD_ID)
        AND (@VEHICLE_ID IS NULL OR T.VEHICLE_ID = @VEHICLE_ID)
        AND (@CARD_TYPE_ID IS NULL OR C.CARD_TYPE_ID = @CARD_TYPE_ID)
    
    ORDER BY T.TRANSACTION_DATE ASC;

	-- YÜKLEME ÝÞLEMLERÝ
	SELECT 
		TU.TOP_UP_TRANSACTION_ID AS 'TRANSACTION ID',
		TU.TOP_UP_TRANSACTION_DATE AS 'TRANSACTION DATE',
		C.CARD_ID AS 'CARD ID',
		C.CARD_NO AS 'CARD NO',
		CT.CARD_TYPE AS 'CARD TYPE',
		TU.TOP_UP_CHANNEL AS 'TOP UP CHANNEL',
		I.INSTITUTION_NAME AS 'INSTITUTION NAME',
		ISNULL(D.DEALER_NAME, 'DÝREKT') AS 'DEALER NAME',
		TU.AMOUNT AS 'TOP UP AMOUNT',
		C.BALANCE AS 'CURRENT BALANCE'

	FROM TOPUPTRANSACTIONS TU
	INNER JOIN CARDS C ON TU.CARD_ID = C.CARD_ID
	INNER JOIN CARDTYPES CT ON C.CARD_TYPE_ID = CT.CARD_TYPE_ID
	INNER JOIN INSTITUTION I ON TU.INSTITUTION_ID = I.INSTITUTION_ID
	LEFT JOIN DEALER D ON TU.DEALER_ID = D.DEALER_ID
	WHERE 
		CAST(TU.TOP_UP_TRANSACTION_DATE AS DATE) BETWEEN CAST(@START_DATE AS DATE) AND CAST(@END_DATE AS DATE)
		AND (@CARD_ID IS NULL OR TU.CARD_ID = @CARD_ID)
	ORDER BY TU.TOP_UP_TRANSACTION_DATE DESC;

  
    -- KART TÝPÝNE GÖRE DAÐILIM
    SELECT 
        CT.CARD_TYPE AS 'CARD TYPE',
        COUNT(T.TRANSACTION_ID) AS 'NUM OF TRANSACTION',
		SUM(T.SPENT_AMOUNT) AS 'SPENT AMOUNT',
        COUNT(DISTINCT T.CARD_ID) AS 'DIFFERENT CARD'
    FROM TRANSACTIONS T
    INNER JOIN CARDS C ON T.CARD_ID = C.CARD_ID
    INNER JOIN CARDTYPES CT ON C.CARD_TYPE_ID = CT.CARD_TYPE_ID
    WHERE 
        CAST(T.TRANSACTION_DATE AS DATE) BETWEEN CAST(@START_DATE AS DATE) AND CAST(@END_DATE AS DATE)
        AND (@CARD_ID IS NULL OR T.CARD_ID = @CARD_ID)
        AND (@VEHICLE_ID IS NULL OR T.VEHICLE_ID = @VEHICLE_ID)
        AND (@CARD_TYPE_ID IS NULL OR C.CARD_TYPE_ID = @CARD_TYPE_ID)
    GROUP BY CT.CARD_TYPE
    ORDER BY COUNT(T.TRANSACTION_ID) DESC;
END;

--------KULLANIM ÖRNEKLERÝ----------

EXEC SP_CARD_USAGE_REPORT
    @START_DATE = '2025-01-01', 
    @END_DATE = '2025-12-31', 
	@CARD_ID = 3;

