CREATE PROCEDURE SP_DASHBOARD_REPORT
AS
BEGIN
    SET NOCOUNT ON;
    
    -- GÜNLÜK ÖZETLER
    
    SELECT 
        'BUGÜN' AS 'PERIOD',
        COUNT(T.TRANSACTION_ID) AS 'NUM OF BOARDINGS',
        SUM(T.SPENT_AMOUNT) AS 'BOARDING INCOME',
        COUNT(TU.TOP_UP_TRANSACTION_ID) AS 'NUM OF TOP UPS',
        SUM(TU.AMOUNT) AS 'AMOUNT OF TOP UPS',
        COUNT(DISTINCT T.CARD_ID) AS 'NUM OF ACTIVE CARDS'
    FROM TRANSACTIONS T
    FULL OUTER JOIN TOPUPTRANSACTIONS TU ON CAST(T.TRANSACTION_DATE AS DATE) = CAST(TU.TOP_UP_TRANSACTION_DATE AS DATE)
    WHERE CAST(COALESCE(T.TRANSACTION_DATE, TU.TOP_UP_TRANSACTION_DATE) AS DATE) = CAST(GETDATE() AS DATE)
    
    UNION ALL
    
    SELECT 
        'DÜN' AS 'PERIOD',
        COUNT(T.TRANSACTION_ID) AS 'NUM OF BOARDINGS',
        SUM(T.SPENT_AMOUNT) AS 'BOARDING INCOME',
        COUNT(TU.TOP_UP_TRANSACTION_ID) AS 'NUM OF TOP UPS',
        SUM(TU.AMOUNT) AS 'AMOUNT OF TOP UPS',
        COUNT(DISTINCT T.CARD_ID) AS 'NUM OF ACTIVE CARDS'
    FROM TRANSACTIONS T
    FULL OUTER JOIN TOPUPTRANSACTIONS TU ON CAST(T.TRANSACTION_DATE AS DATE) = CAST(TU.TOP_UP_TRANSACTION_DATE AS DATE)
    WHERE CAST(COALESCE(T.TRANSACTION_DATE, TU.TOP_UP_TRANSACTION_DATE) AS DATE) = CAST(DATEADD(DAY, -1, GETDATE()) AS DATE)
    
    UNION ALL
    
    SELECT 
        'BU HAFTA' AS 'PERIOD',
        COUNT(T.TRANSACTION_ID) AS 'NUM OF BOARDINGS',
        SUM(T.SPENT_AMOUNT) AS 'BOARDING INCOME',
        COUNT(TU.TOP_UP_TRANSACTION_ID) AS 'NUM OF TOP UPS',
        SUM(TU.AMOUNT) AS 'AMOUNT OF TOP UPS',
        COUNT(DISTINCT T.CARD_ID) AS 'NUM OF ACTIVE CARDS'
    FROM TRANSACTIONS T
    FULL OUTER JOIN TOPUPTRANSACTIONS TU ON CAST(T.TRANSACTION_DATE AS DATE) = CAST(TU.TOP_UP_TRANSACTION_DATE AS DATE)
    WHERE CAST(COALESCE(T.TRANSACTION_DATE, TU.TOP_UP_TRANSACTION_DATE) AS DATE) >= CAST(DATEADD(DAY, -7, GETDATE()) AS DATE);

END;

EXEC SP_DASHBOARD_REPORT