-- To execute the stored procedure, use the following format:
-- EXEC SP_SIMULATEBOARDINGS 'START_DATE', 'END_DATE', VEHICLE_ID, RECORD_COUNT
-- If VEHICLE_ID is NULL, transactions will be created for all vehicles.

CREATE PROCEDURE SP_SIMULATEBOARDINGS
@START_DATE DATETIME,
@END_DATE DATETIME,
@VEHICLE_ID INT = NULL, -- NULL OLDUÐU ZAMAN TÜM ARAÇLARDAN BÝRÝ
@RECORD_COUNT INT = 2 -- OLUÞTURULACAK KAYIT SAYISI
AS
BEGIN --MAIN
    SET NOCOUNT ON;
    
    -- DEÐÝÞKENLER
    DECLARE @COUNTER INT = 1 -- SAYAÇ
    DECLARE @SUCCESS_COUNT INT = 0 -- BAÞARILI KAYIT SAYISI
    DECLARE @RANDOM_DATE_TIME DATETIME --RANDOM  TARÝH 
    DECLARE @RANDOM_CARD_ID INT -- RANDOM KART ID 
    DECLARE @CARD_NO INT -- KART NO
    DECLARE @CARD_TYPE_ID INT --KART TÝPÝ ID
    DECLARE @CURRENT_BALANCE DECIMAL(10,2) -- ÞÝMDÝKÝ BAKÝYE
    DECLARE @FARE_PRICE DECIMAL(10,2) -- ÜCRET FÝYAT
    DECLARE @SELECTED_VEHICLE_ID INT; -- SEÇÝLEN ARAÇ ID
    DECLARE @AVAILABLE_CARDS_COUNT INT --UYGUN KART SAYISI
    DECLARE @AVAILABLE_VEHICLES_COUNT INT --UYGUN ARAÇ SAYISI
    
	-- PARAMETRE KONTROLLERÝ
	-- DATE KONTROLLERÝ
    IF @START_DATE >= @END_DATE
    BEGIN --1
		PRINT 'BAÞLANGIÇ TARÝHÝ BÝTÝÞ TARÝHÝNDEN KÜÇÜK OLMALI'
        RETURN
    END --1
    
	-- EÐER KAYIT SAYISI KÜÇÜKSE
    IF @RECORD_COUNT <= 0
    BEGIN --2
		PRINT 'KAYIT SAYISI 0''DAN BÜYÜK OLMALI'
        RETURN
    END --2
    
    -- KULLANILABÝLÝR KART SAYISI KONTROLÜ
    SELECT @AVAILABLE_CARDS_COUNT = COUNT(*) FROM CARDS -- SATIR SAYISINI DÖNDÜR
    WHERE ISACTIVE = 1 AND BALANCE > 0; -- KART AKTÝF OLMALI VE BAKÝYESÝ 0DEN BÜYÜK OLMALI
    
	-- EÐER KULLANILABÝLÝR KART YOKSA
    IF @AVAILABLE_CARDS_COUNT = 0
    BEGIN --3
        PRINT 'KULLANILABÝLÝR KART YOK'
        RETURN
    END --3
    

    -- ARAÇ KONTROLÜ
    IF @VEHICLE_ID IS NOT NULL --EÐER ARAÇ ID NULL DEÐÝLSE
    BEGIN --4
		
        IF NOT EXISTS (SELECT 1 FROM VEHICLE WHERE VEHICLE_ID = @VEHICLE_ID AND ISACTIVE = 1)
        BEGIN --4.1
			PRINT 'BELÝRTÝLEN ARAÇ BULUNAMADI VEYA AKTÝF DEÐÝL'
            RETURN
        END --4.1
		-- KUULANILABÝLÝR ARAÇ SAYISINI 1E EÞÝTLE
        SET @AVAILABLE_VEHICLES_COUNT = 1;
    END --4
    ELSE
    BEGIN --5
		-- KULLANILABÝLÝR ARAÇ SAYISINI SA VE AKTÝFÝ TRUE OLAN ARACI SEÇ
        SELECT @AVAILABLE_VEHICLES_COUNT = COUNT(*) FROM VEHICLE WHERE ISACTIVE = 1
        
		-- EÐER KULLANILABÝLÝR ARAÇ SAYISI 0'A EÞÞÝTSE
        IF @AVAILABLE_VEHICLES_COUNT = 0
        BEGIN --5.1 
			PRINT 'AKTÝF ARAÇ BULUNAMADI'
            RETURN
        END --5.1
    END --5
  

    WHILE @COUNTER <= @RECORD_COUNT AND @SUCCESS_COUNT < @RECORD_COUNT
    BEGIN --6
		-- BAÞLANGIÇ TARÝHÝ VE BÝTÝÞ TARÝHÝ ARASINDA RANDOM TARÝH SEÇ
        SET @RANDOM_DATE_TIME = DATEADD(SECOND, CAST(RAND() * DATEDIFF(SECOND, @START_DATE, @END_DATE) AS INT), @START_DATE)


        -- ARAÇ SEÇÝMÝ
        IF @VEHICLE_ID IS NULL
        BEGIN --6.1
			-- ARAÇLAR TABLOSUNDAN AKÝTF OLAN ARAÇLARDAN RASTEGELE ARAÇ SEÇTÝK
            SELECT TOP 1 @SELECTED_VEHICLE_ID = VEHICLE_ID FROM VEHICLE WHERE ISACTIVE= 1 ORDER BY NEWID();
        END --6.1
        ELSE
        BEGIN --6.2
			-- SEÇÝLEN ARAÇ ID ÝLE ARAÇ ID EÞÝTLEDÝK
            SET @SELECTED_VEHICLE_ID = @VEHICLE_ID;
        END --6.2
        

        -- YETERLÝ BAKÝYESÝ OLAN AKTÝF OLAN KARTLARDAN NEWID ÝLE SEÇTÝK
        SELECT TOP 1 
            @RANDOM_CARD_ID = CARD_ID,
            @CARD_NO = CARD_NO,
            @CARD_TYPE_ID = CARD_TYPE_ID,
            @CURRENT_BALANCE = BALANCE
        FROM CARDS WHERE ISACTIVE = 1 AND BALANCE > 0 ORDER BY NEWID()
        

        IF @RANDOM_CARD_ID IS NOT NULL
        BEGIN --6.3
            -- KART TÝPÝNE GÖRE ÜCRET AL
            SELECT @FARE_PRICE = PRICE FROM CARDTYPES WHERE CARD_TYPE_ID = @CARD_TYPE_ID AND ISACTIVE = 1
            
			-- BAKÝYE KONTROLÜ
            IF @CURRENT_BALANCE >= @FARE_PRICE -- EEÐER MEVCUT BAKÝYE, ÜCRETTEN FAZLA ÝSE
            BEGIN --6.3.1
                BEGIN TRY -- 6.3.1.A
                    -- TRANSACTION BAÞLAT
                    BEGIN TRANSACTION;
                    
                    -- TRANSA. KAYDI OLUÞTUR
                    INSERT INTO TRANSACTIONS(VEHICLE_ID, CARD_ID, CARD_NO, CARD_TYPE_ID, TRANSACTION_DATE, SPENT_AMOUNT, REMAINING_BALANCE)
                    VALUES(@SELECTED_VEHICLE_ID, @RANDOM_CARD_ID, @CARD_NO, @CARD_TYPE_ID, @RANDOM_DATE_TIME, @FARE_PRICE, @CURRENT_BALANCE - @FARE_PRICE);
                    
                    -- KART BAKÝYESÝNÝ GÜNCELLE
                    UPDATE CARDS
                    SET BALANCE = BALANCE - @FARE_PRICE, MODIFIED_DATE = GETDATE() WHERE CARD_ID = @RANDOM_CARD_ID;
					-- KART IDSÝ, RANDOM KART ID'SÝNE EÞÝT OLAN KARTLARIN BAKÝYESÝNÝ, BAKÝYEDE KALAN SAYI ÝLE GÜNCELLE, MODIFIED DATE ÝÇÝN GETDATE AL .
                    
                    -- TRANSACTION ONAYLA
                    COMMIT TRANSACTION;
                    
					-- BÞARILI KAYIT SAYISINI 1 ARTTIR
                    SET @SUCCESS_COUNT = @SUCCESS_COUNT + 1;

                END TRY --6.3.1.A
                BEGIN CATCH --6.3.1.B
                    -- HATA OLURSA ÝÞLEMÝ GERÝ AL
                    IF @@TRANCOUNT > 0
                        ROLLBACK TRANSACTION;
                   
                END CATCH --6.3.1.B
			END --6.3.1
        END --6.3
        
        -- DEÐÝÞKENLERÝ SIFIRLA
        SET @RANDOM_CARD_ID = NULL;
        SET @CARD_NO = NULL;
        SET @COUNTER = @COUNTER + 1;
      
    END --6
    
    -- OLUÞTURULAN TRANSACTIONLARI GÖSTER
    IF @SUCCESS_COUNT > 0
    BEGIN --7
        SELECT TOP (@SUCCESS_COUNT)
            T.TRANSACTION_ID,
            V.PLATE,
			T.CARD_ID,
            T.CARD_NO,
            CT.CARD_TYPE,
            T.TRANSACTION_DATE,
            T.SPENT_AMOUNT,
            T.REMAINING_BALANCE
        FROM TRANSACTIONS T
        INNER JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
        INNER JOIN CARDTYPES CT ON T.CARD_TYPE_ID = CT.CARD_TYPE_ID
        ORDER BY T.TRANSACTION_ID DESC;
    END --7

	SELECT * FROM TRANSACTIONS
END -- MAIN


-- DENEME KISMI
 EXEC SP_SIMULATEBOARDINGS 
     @START_DATE = '2025-01-01',
     @END_DATE = '2025-01-10', 
     @VEHICLE_ID = NULL,  
     @RECORD_COUNT = 2;
