CREATE PROCEDURE SP_TOPUP_REPORT_SON
@START_DATE DATETIME = NULL,
@END_DATE DATETIME = NULL,
@INSTITUTION_ID INT = NULL,
@DEALER_ID INT = NULL,
@CARD_TYPE_ID INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
	-- VARSAYILAN TARÝH ARALIÐI (SON 30 GÜN)
    IF @START_DATE IS NULL SET @START_DATE = DATEADD(DAY, -30, GETDATE())
    IF @END_DATE IS NULL SET @END_DATE = GETDATE()
    
    SELECT 
        -- TEMEL BÝLGÝLER
        T.TOP_UP_TRANSACTION_ID AS 'TRANSACTION ID',
        T.TOP_UP_TRANSACTION_DATE AS 'TRANSACTION DATE',
        T.AMOUNT AS 'AMOUNT',
        T.TOP_UP_CHANNEL AS 'CHANNEL',
        
        -- KART BÝLGÝLERÝ
        C.CARD_ID AS 'CARD ID',
        C.CARD_NO AS 'CARD NO',
        CT.CARD_TYPE AS 'CARD TYPE',
        
        -- KURUM BÝLGÝLERÝ
        I.INSTITUTION_NAME AS 'INSTITUTION',
        I.INSTITUTION_ADDRESS AS 'INSTITUTION ADDRESS',
        
        -- DEALER BÝLGÝLERÝ
        D.DEALER_NAME AS 'DEALER',
        D.DEALER_ADRESS AS 'DEALER ADDRESS',
        
        -- POS BÝLGÝLERÝ
        P.POS_CODE AS 'POS CODE',
        P.POS_LOCATION AS 'POS LOCATION'
        
    FROM TOPUPTRANSACTIONS T
    INNER JOIN CARDS C ON T.CARD_ID = C.CARD_ID
    INNER JOIN CARDTYPES CT ON C.CARD_TYPE_ID = CT.CARD_TYPE_ID
    INNER JOIN INSTITUTION I ON T.INSTITUTION_ID = I.INSTITUTION_ID
    LEFT JOIN DEALER D ON T.DEALER_ID = D.DEALER_ID
    LEFT JOIN POS P ON T.POS_ID = P.POS_ID
    
    WHERE 
        CAST(T.TOP_UP_TRANSACTION_DATE AS DATE) BETWEEN CAST(@START_DATE AS DATE) AND CAST(@END_DATE AS DATE)
        AND (@INSTITUTION_ID IS NULL OR T.INSTITUTION_ID = @INSTITUTION_ID)
        AND (@DEALER_ID IS NULL OR T.DEALER_ID = @DEALER_ID)
        AND (@CARD_TYPE_ID IS NULL OR C.CARD_TYPE_ID = @CARD_TYPE_ID)
    
    ORDER BY T.TOP_UP_TRANSACTION_DATE DESC;
    
    -- ÖZET BÝLGÝLER
    
    SELECT 
        'KURUM BAZLI ÖZET' AS 'REPORT TYPE',
        I.INSTITUTION_NAME AS 'INSTITUTION',
        CT.CARD_TYPE AS 'CARD TYPE',
        COUNT(*) AS 'TOTAL TRANSACTION',
        SUM(T.AMOUNT) AS 'TOTAL TOP UP',
        AVG(T.AMOUNT) AS 'AVG TOP UP'
    FROM TOPUPTRANSACTIONS T
    INNER JOIN CARDS C ON T.CARD_ID = C.CARD_ID
    INNER JOIN CARDTYPES CT ON C.CARD_TYPE_ID = CT.CARD_TYPE_ID
    INNER JOIN INSTITUTION I ON T.INSTITUTION_ID = I.INSTITUTION_ID
    WHERE 
        CAST(T.TOP_UP_TRANSACTION_DATE AS DATE) BETWEEN CAST(@START_DATE AS DATE) AND CAST(@END_DATE AS DATE)
        AND (@INSTITUTION_ID IS NULL OR T.INSTITUTION_ID = @INSTITUTION_ID)
        AND (@DEALER_ID IS NULL OR T.DEALER_ID = @DEALER_ID)
        AND (@CARD_TYPE_ID IS NULL OR C.CARD_TYPE_ID = @CARD_TYPE_ID)
    GROUP BY I.INSTITUTION_NAME, CT.CARD_TYPE
    ORDER BY SUM(T.AMOUNT) DESC;

END;


EXEC SP_TOPUP_REPORT_SON
    @START_DATE = '2024-01-01', 
    @END_DATE = '2030-01-01', 
	@DEALER_ID = 2;
    @INSTITUTION_ID = 1;