-- KART YÜKLEME SONRASI BAKÝYE GÜNCELLEMESÝ
CREATE TRIGGER TRG_TOPUP_UPDATE_BALANCE
ON TOPUPTRANSACTIONS
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
	
	-- YENÝ EKLENEN KAYITLAR ÝÇÝN BAKÝYE GÜNCELLEME
    UPDATE C
    SET BALANCE = C.BALANCE + I.AMOUNT,
        MODIFIED_DATE = GETDATE()
    FROM CARDS C
    INNER JOIN INSERTED I ON C.CARD_ID = I.CARD_ID
    WHERE C.ISACTIVE = 1;
    
	-- GÜNCELLENEN KART SAYISINI BÝLDÝR
    DECLARE @UPDATED_COUNT INT = @@ROWCOUNT;
    IF @UPDATED_COUNT > 0
END