CREATE TRIGGER TRG_VEHICLE_VALIDATOR_CHECK
ON VEHICLE
AFTER INSERT, UPDATE
AS
BEGIN --1

	SET NOCOUNT ON

	-- DEÐÝÞKENLER
	DECLARE @VALIDATOR_NO INT
	DECLARE @PLATE_NO VARCHAR(20)

	IF EXISTS (
		SELECT 1 FROM INSERTED I
		INNER JOIN VALIDATOR V
		ON 
		I.VALIDATOR_NO = V.VALIDATOR_NO
		WHERE V.ISACTIVE = 1 AND I.ISACTIVE = 1
		-- SADECE AKTÝF ARAÇLAR VE VALIDATORLER ÝÇÝN KONTROL EDÝLÝR
		AND EXISTS (
		SELECT 1 FROM VEHICLE V2 WHERE V2.VALIDATOR_NO = I.VALIDATOR_NO
		AND V2.ISACTIVE = 1 
		AND V2.VEHICLE_ID != I.VEHICLE_ID -- KENDÝSÝNÝ HARÝÇ TUTTUK
		)
	)
	
	BEGIN -- 2
		-- HATALI VALIDATOR BÝLGÝLERÝNÝ AL
		SELECT TOP 1
		@VALIDATOR_NO = I.VALIDATOR_NO,
		@PLATE_NO = I.PLATE FROM INSERTED I
		WHERE EXISTS (
		SELECT 1 FROM VEHICLE V2
		WHERE V2.VALIDATOR_NO = I.VALIDATOR_NO
		AND V2.ISACTIVE = 1
		AND V2.VEHICLE_ID = I.VEHICLE_ID
		)
	END --2

	-- VALIDATOR SÝSTEMDE KAYITLI MI
	IF EXISTS ( 
		SELECT 1 FROM INSERTED I
		WHERE NOT EXISTS (
		SELECT 1 FROM VALIDATOR V
		WHERE V.VALIDATOR_NO = I.VALIDATOR_NO
		AND V.ISACTIVE = 1
		)
	)

	BEGIN -- 3
		SELECT TOP 1 
		@VALIDATOR_NO = I.VALIDATOR_NO,
		@PLATE_NO = I.PLATE FROM INSERTED I
		WHERE NOT EXISTS (
		SELECT 1 FROM VALIDATOR V
		WHERE V.VALIDATOR_NO = I.VALIDATOR_NO
		AND V.ISACTIVE = 1
		)
	END --3

END --1

/*
-------------DENEMELEER --------------------

-- 1001 NUMARALI VALIDATOR ATANDIÐI ÝÇÝN BU KOD ÇALIÞMAZ
INSERT INTO VEHICLE (PLATE, VALIDATOR_NO, VEHICLE_BRAND, VEHICLE_MODEL)
VALUES ('34LFE8545', 1001, 'SRWE', 'WERE' )


-- 1007 HUMARALI VALIDATOR HÝÇBÝR ARACA ATANMADIÐI ÝÇÝN BU KOD ÇALIÞIR
INSERT INTO VEHICLE (PLATE, VALIDATOR_NO ,VEHICLE_BRAND, VEHICLE_MODEL)
VALUES ('45TTY55', 1007, 'LKRJR', 'KRJLK') 

-- BU KODUN ÇALIÞMAMASI LAZIM AMA !!!!!!!!!!!!!!!!!!!!!!
UPDATE VEHICLE SET VEHICLE_BRAND = 'KMGM' WHERE VALIDATOR_NO = '1002'

-- BU KOD ÇALIÞMAMALI
UPDATE VEHICLE SET VALIDATOR_NO = '1001' WHERE VEHICLE_BRAND = 'Ford'

*/