-- VEHICLE-VALIDATOR ÝLÝÞKÝSÝ
CREATE TRIGGER TRG_VEHICLE_VALIDATOR_CHECK
ON VEHICLE
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    
	-- AYNI VALIDATOR BÝRDEN FAZLA ARAÇTA KULLANILIRSA HATA VER
    IF EXISTS (
        SELECT VALIDATOR_NO
        FROM VEHICLE V
        WHERE V.ISACTIVE = 1
        AND V.VALIDATOR_NO IN (SELECT VALIDATOR_NO FROM INSERTED)
        GROUP BY VALIDATOR_NO
        HAVING COUNT(*) > 1
    )
    BEGIN
		RAISERROR('HATA: AYNI VALIDATOR BÝRDEN FAZLA AKTÝF ARAÇTA KULLANILAMAZ. ', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
    
	-- VALIDATOR SÝSTEMDE KAYITLI DEÐÝLSE HATA VER
    IF EXISTS (
        SELECT 1 FROM INSERTED I
        WHERE NOT EXISTS (
            SELECT 1 FROM VALIDATOR V
            WHERE V.VALIDATOR_NO = I.VALIDATOR_NO AND V.ISACTIVE = 1
        )
    )
    BEGIN
		RAISERROR('HATA: BELÝRTÝLEN VALIDATOR BULUNAMADI VEYA AKTÝF DEÐÝL. ', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END
END;